version: 2.1

orbs:
  android: circleci/android@2

jobs:
  build:
    executor:
      name: android/android-machine
      tag: 2022.09.1
    
    steps:
      - checkout

      - run:
          name: install flutter
          command: |
            ./install.sh

      - run:
          name: Build APK
          command: |
            flutter build apk --target-platform android-arm64
            

      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
