version: 2.1

orbs:
  android: circleci/android@2
  flutter: circleci/flutter@1.1.0

jobs:
  build:
    executor:
      name: android/android-machine
      tag: 2022.09.1
    
    steps:
      - checkout

      - flutter/install_sdk: 
          version: 3.7.12

      - flutter/install_pub:
          cache-version: v1

      - run:
          name: Flutter pub get
          command: |
            flutter pub get

      - run:
          name: Build APK
          command: |
            flutter build apk --target-platform android-arm64
            

      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
