version: 2.1

executors:
  android-flutter:
    docker:
      - image: gmemstr/flutter-fastlane:latest
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'
jobs:
  beta_deploy:
    executor: android-flutter
    steps:
      - checkout
      - run: export codehome=$PWD
      - run: cd /home/cirrus/sdks && rm -rf flutter
      - run: git clone --depth 1 https://github.com/flutter/flutter
      - run: sudo export PATH=/home/cirrus/sdks/flutter/bin:$PATH && ls /home/cirrus/sdks/flutter/bin
      - run: cd $codehome && flutter build apk --target-platform android-arm64

workflows:
  deploy:
    jobs:
      - beta_deploy:
          filters:
            branches:
              only: master