version: 2.1

orbs:
  android: circleci/android@2

jobs:
  build:
    executor:
      name: android/android-machine
      tag: 2022.09.1
    
    steps:
      - checkout

      - run
          name: install flutter
          command: |
            mkdir -p ~/development
            curl -o flutter.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/beta/linux/flutter_linux_3.10.0-1.5.pre-beta.tar.xz
            tar xf flutter.tar.xz -C ~/development
            rm -f flutter.tar.xz
            echo 'export PATH=~/development/flutter/bin:$PATH' >> $BASH_ENV

      - run:
          name: Build APK
          command: |
            flutter build apk --target-platform android-arm64
            

      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
